- Fixes to general readme. - Improvements to git pre-commit hook. - Split crop function into two overloaded versions, one receives a vector of nodes and the other receives an xpath string. - The crop function base_xpath parameter can now be any expression, even relative to Coords node.

diff --git a/githook-pre-commit b/githook-pre-commit
--- a/githook-pre-commit
+++ b/githook-pre-commit
@@ -29,7 +29,7 @@ V=$(date -u +%Y.%m.%d);
 
 check_change_after_staged () {
   [ "${2:1:1}" = "M" ] &&
-    echo "${0##*/}: error: aborting due to file change after staged: $1" 1>&2 &&
+    echo "${0##*/}: error: aborting due to file change: $1" 1>&2 &&
     exit 1;
 }
 
@@ -47,29 +47,24 @@ already_updated () {
 
 n=1;
 while [ "$n" -lt "${#FILES[@]}" ]; do
+  check_change_after_staged "${FILES[$n]}" "${FILES[$((n-1))]}";
   [ $(already_updated "${FILES[$n]}") = 0 ] &&
     case "${FILES[$n]}" in
       *.cc )
-        check_change_after_staged "${FILES[$n]}" "${FILES[$((n-1))]}";
         update_file_version "${FILES[$n]}";
         [ -e "${FILES[$n]/.cc/.h}" ] &&
           update_file_version "${FILES[$n]/.cc/.h}";
         ;;
       *.h )
-        check_change_after_staged "${FILES[$n]}" "${FILES[$((n-1))]}";
         update_file_version "${FILES[$n]}";
         [ -e "${FILES[$n]/.h/.cc}" ] &&
           update_file_version "${FILES[$n]/.h/.cc}";
         ;;
       *.py )
-        check_change_after_staged "${FILES[$n]}" "${FILES[$((n-1))]}";
         update_file_version "${FILES[$n]}";
         echo "${0##*/}: pylint --errors-only --extension-pkg-whitelist=cv2 ${FILES[$n]}" 1>&2;
         pylint --errors-only --extension-pkg-whitelist=cv2 "${FILES[$n]}";
         [ "$?" != 0 ] && exit 1;
-        ;;
-      *.rst | githook-pre-commit )
-        check_change_after_staged "${FILES[$n]}" "${FILES[$((n-1))]}";
         ;;
     esac
   n=$((n+2));
